# -*- coding: utf-8 -*-
"""craglist(linear regression).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIyfC3ewIXwQk03zeKXKo9FIhjeo5kXs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
a=LinearRegression()
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
scl=StandardScaler()
df=pd.read_csv('/content/craiglist.csv')
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.fillna("Honda",inplace=True)
d={"Nissan":1,"Lexus":2,"hyundai":3,"Honda":4,"Infiniti":5,"Dodge":6,"Chevrolet":7,"hyundai":8,"Volvo":9,"Chrysler":10,"Ford":11,"chevy":12}
df["make"]=df["make"].map(d)
d={"excellent":1,"good":2,"like new":3,"new":4,"fair":5}
df["condition"]=df["condition"].map(d)
m=df["condition"].mean()
df.fillna(m,inplace=True)
x=df[["condition","odometer","make","year"]]
y=df["price"]
scl.fit_transform(x)
# train test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=0)
a.fit (x_train,y_train)
y_pred=a.predict(x_test)
print(y_pred)
print('_________')
print(y_test)


from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print(mse)
print(rmse)