# -*- coding: utf-8 -*-
"""customer purchasing(linear_regression).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbLqfGfg3ZuKYMCnuGpAhPSJNpa5mrYp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

path='//content/Customer Purchasing Behaviors.csv'
df=pd.read_csv(path)
print(df)

X = df["annual_income"].values
Y = df["purchase_amount"].values
#print(X)
#print(Y)

#model Initialization
reg = LinearRegression()

m = len(X)
X=X.reshape((m,1))
#model Fitting
reg = reg.fit(X,Y)

#y prediction
Y_prediction = reg.predict(X)
#print(Y_prediction)

#Model Evaluation
rmse = np.sqrt(mean_squared_error(Y,Y_prediction))
print(rmse)