# -*- coding: utf-8 -*-
"""iphone(knn).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U30FEkidsuGgX7erm6g9B4L_mz25B4nY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path='/content/iphone_purchase_record.csv'
data=pd.read_csv(path)
data.head()

from sklearn import preprocessing
le=preprocessing.LabelEncoder()
data['Gender']=le.fit_transform(data['Gender'])
data.head()

x=data[['Gender','Age','Salary']]
y=data['Purchase Iphone']
print(x,y)

from sklearn.model_selection import train_test_split
x_train ,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train)
print(x_test)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train =scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

from sklearn.neighbors import KNeighborsClassifier
k=3
knn=KNeighborsClassifier(n_neighbors=k)
knn.fit(x_train,y_train)

y_pred= knn.predict(x_test)
print(y_pred)

from sklearn import metrics
cnf_matrix=metrics.confusion_matrix(y_test,y_pred)
cnf_matrix

print("accuracy:",metrics.accuracy_score(y_test,y_pred))
print("precision:",metrics.precision_score(y_test,y_pred))
print("recall:",metrics.recall_score(y_test,y_pred))
print("f1 score:",metrics.f1_score(y_test,y_pred))