# -*- coding: utf-8 -*-
"""Weight_height(Knn).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DD8bzS09ajnf9p0CZVJRY2l-mmW5f2Ag
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

path='/content/weight_height.csv'
data=pd.read_csv(path)
data.head()

x=data[['weight(x)','height(y)']].values
y=data['class'].values
print(x,y)

x_train, x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=42)

knn=KNeighborsClassifier(n_neighbors=3)

knn.fit(x_train,y_train)
data=np.array([[57,170]])

y_pred=knn.predict(data)

print(y_pred)
print(data)